
hw2_1NF_invalidPKK1K2
;
SELECT k1,k2,a FROM hw2_1NF_invalidPKK1K2;
SELECT * FROM hw2_1NF_invalidPKK1K2;
SELECT k1,k2,COUNT(*) FROM hw2_1NF_invalidPKK1K2
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,COUNT(*) FROM hw2_1NF_invalidPKK1K2
GROUP BY k1,k2,a
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_1NF_invalidPKK1K2
GROUP BY a
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_1NF_invalidPKK1K2
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1

hw2_1nf_difficult
;
SELECT k1,k2,a,b,c,d,e,f FROM hw2_1nf_difficult;
SELECT * FROM hw2_1nf_difficult;
SELECT k1,k2,COUNT(*) FROM hw2_1nf_difficult
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,b,c,d,e,f,COUNT(*) FROM hw2_1nf_difficult
GROUP BY k1,k2,a,b,c,d,e,f
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_1nf_difficult
GROUP BY a
HAVING COUNT(*) > 1;
SELECT b,COUNT(*) FROM hw2_1nf_difficult
GROUP BY b
HAVING COUNT(*) > 1;
SELECT c,COUNT(*) FROM hw2_1nf_difficult
GROUP BY c
HAVING COUNT(*) > 1;
SELECT d,COUNT(*) FROM hw2_1nf_difficult
GROUP BY d
HAVING COUNT(*) > 1;
SELECT e,COUNT(*) FROM hw2_1nf_difficult
GROUP BY e
HAVING COUNT(*) > 1;
SELECT f,COUNT(*) FROM hw2_1nf_difficult
GROUP BY f
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_1nf_difficult
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_1nf_difficult
GROUP BY k1
HAVING COUNT(DISTINCT b) > 1;
SELECT k1,COUNT(DISTINCT c) FROM hw2_1nf_difficult
GROUP BY k1
HAVING COUNT(DISTINCT c) > 1;
SELECT k1,COUNT(DISTINCT d) FROM hw2_1nf_difficult
GROUP BY k1
HAVING COUNT(DISTINCT d) > 1;
SELECT k1,COUNT(DISTINCT e) FROM hw2_1nf_difficult
GROUP BY k1
HAVING COUNT(DISTINCT e) > 1;
SELECT k1,COUNT(DISTINCT f) FROM hw2_1nf_difficult
GROUP BY k1
HAVING COUNT(DISTINCT f) > 1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_1nf_difficult
GROUP BY k2
HAVING COUNT(DISTINCT a) > 1;
SELECT k2,COUNT(DISTINCT b) FROM hw2_1nf_difficult
GROUP BY k2
HAVING COUNT(DISTINCT b) > 1;
SELECT k2,COUNT(DISTINCT c) FROM hw2_1nf_difficult
GROUP BY k2
HAVING COUNT(DISTINCT c) > 1;
SELECT k2,COUNT(DISTINCT d) FROM hw2_1nf_difficult
GROUP BY k2
HAVING COUNT(DISTINCT d) > 1

hw2_2nf_not3nf
;
SELECT k,a,b,c FROM hw2_2nf_not3nf;
SELECT * FROM hw2_2nf_not3nf;
SELECT k,COUNT(*) FROM hw2_2nf_not3nf
GROUP BY k
HAVING COUNT(*) > 1;
SELECT k,a,b,c,COUNT(*) FROM hw2_2nf_not3nf
GROUP BY k,a,b,c
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_2nf_not3nf
GROUP BY a
HAVING COUNT(*) > 1;
SELECT b,COUNT(*) FROM hw2_2nf_not3nf
GROUP BY b
HAVING COUNT(*) > 1;
SELECT c,COUNT(*) FROM hw2_2nf_not3nf
GROUP BY c
HAVING COUNT(*) > 1;
SELECT a,COUNT(DISTINCT b) FROM hw2_2nf_not3nf
GROUP BY a
HAVING COUNT(DISTINCT b)>1;
SELECT a,COUNT(DISTINCT c) FROM hw2_2nf_not3nf
GROUP BY a
HAVING COUNT(DISTINCT c)>1;
SELECT b,COUNT(DISTINCT a) FROM hw2_2nf_not3nf
GROUP BY b
HAVING COUNT(DISTINCT a)>1;
SELECT b,COUNT(DISTINCT c) FROM hw2_2nf_not3nf
GROUP BY b
HAVING COUNT(DISTINCT c)>1

hw2_3nf_notbcnf
;
SELECT k1,k2,a,b FROM hw2_3nf_notbcnf;
SELECT * FROM hw2_3nf_notbcnf;
SELECT k1,k2,COUNT(*) FROM hw2_3nf_notbcnf
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,b,COUNT(*) FROM hw2_3nf_notbcnf
GROUP BY k1,k2,a,b
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_3nf_notbcnf
GROUP BY a
HAVING COUNT(*) > 1;
SELECT b,COUNT(*) FROM hw2_3nf_notbcnf
GROUP BY b
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_3nf_notbcnf
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_3nf_notbcnf
GROUP BY k1
HAVING COUNT(DISTINCT b) > 1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_3nf_notbcnf
GROUP BY k2
HAVING COUNT(DISTINCT a) > 1;
SELECT k2,COUNT(DISTINCT b) FROM hw2_3nf_notbcnf
GROUP BY k2
HAVING COUNT(DISTINCT b) > 1;
SELECT a,COUNT(DISTINCT b) FROM hw2_3nf_notbcnf
GROUP BY a
HAVING COUNT(DISTINCT b)>1;
SELECT b,COUNT(DISTINCT a) FROM hw2_3nf_notbcnf
GROUP BY b
HAVING COUNT(DISTINCT a)>1;
SELECT a,COUNT(DISTINCT k1) FROM hw2_3nf_notbcnf
GROUP BY a
HAVING COUNT(DISTINCT k1)>1;
SELECT a,COUNT(DISTINCT k2) FROM hw2_3nf_notbcnf
GROUP BY a
HAVING COUNT(DISTINCT k2)>1

hw2_3nf_notbcnf_2
;
SELECT k1,k2,a,b FROM hw2_3nf_notbcnf_2;
SELECT * FROM hw2_3nf_notbcnf_2;
SELECT k1,k2,COUNT(*) FROM hw2_3nf_notbcnf_2
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,b,COUNT(*) FROM hw2_3nf_notbcnf_2
GROUP BY k1,k2,a,b
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_3nf_notbcnf_2
GROUP BY a
HAVING COUNT(*) > 1;
SELECT b,COUNT(*) FROM hw2_3nf_notbcnf_2
GROUP BY b
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_3nf_notbcnf_2
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_3nf_notbcnf_2
GROUP BY k1
HAVING COUNT(DISTINCT b) > 1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_3nf_notbcnf_2
GROUP BY k2
HAVING COUNT(DISTINCT a) > 1;
SELECT k2,COUNT(DISTINCT b) FROM hw2_3nf_notbcnf_2
GROUP BY k2
HAVING COUNT(DISTINCT b) > 1;
SELECT a,COUNT(DISTINCT b) FROM hw2_3nf_notbcnf_2
GROUP BY a
HAVING COUNT(DISTINCT b)>1;
SELECT b,COUNT(DISTINCT a) FROM hw2_3nf_notbcnf_2
GROUP BY b
HAVING COUNT(DISTINCT a)>1;
SELECT a,COUNT(DISTINCT k1) FROM hw2_3nf_notbcnf_2
GROUP BY a
HAVING COUNT(DISTINCT k1)>1;
SELECT a,COUNT(DISTINCT k2) FROM hw2_3nf_notbcnf_2
GROUP BY a
HAVING COUNT(DISTINCT k2)>1

hw2_bcnf
;
SELECT k1,k2,a,b FROM hw2_bcnf;
SELECT * FROM hw2_bcnf;
SELECT k1,k2,COUNT(*) FROM hw2_bcnf
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,b,COUNT(*) FROM hw2_bcnf
GROUP BY k1,k2,a,b
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_bcnf
GROUP BY a
HAVING COUNT(*) > 1;
SELECT b,COUNT(*) FROM hw2_bcnf
GROUP BY b
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_bcnf
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_bcnf
GROUP BY k1
HAVING COUNT(DISTINCT b) > 1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_bcnf
GROUP BY k2
HAVING COUNT(DISTINCT a) > 1;
SELECT k2,COUNT(DISTINCT b) FROM hw2_bcnf
GROUP BY k2
HAVING COUNT(DISTINCT b) > 1;
SELECT a,COUNT(DISTINCT b) FROM hw2_bcnf
GROUP BY a
HAVING COUNT(DISTINCT b)>1;
SELECT b,COUNT(DISTINCT a) FROM hw2_bcnf
GROUP BY b
HAVING COUNT(DISTINCT a)>1;
SELECT a,COUNT(DISTINCT k1) FROM hw2_bcnf
GROUP BY a
HAVING COUNT(DISTINCT k1)>1;
SELECT a,COUNT(DISTINCT k2) FROM hw2_bcnf
GROUP BY a
HAVING COUNT(DISTINCT k2)>1;
SELECT b,COUNT(DISTINCT k1) FROM hw2_bcnf
GROUP BY b
HAVING COUNT(DISTINCT k1)>1;
SELECT b,COUNT(DISTINCT k2) FROM hw2_bcnf
GROUP BY b
HAVING COUNT(DISTINCT k2)>1

hw2_bcnf_2
;
SELECT id1,id2,col1,col2 FROM hw2_bcnf_2;
SELECT * FROM hw2_bcnf_2;
SELECT id1,id2,COUNT(*) FROM hw2_bcnf_2
GROUP BY id1,id2
HAVING COUNT(*) > 1;
SELECT id1,id2,col1,col2,COUNT(*) FROM hw2_bcnf_2
GROUP BY id1,id2,col1,col2
HAVING COUNT(*) > 1;
SELECT col1,COUNT(*) FROM hw2_bcnf_2
GROUP BY col1
HAVING COUNT(*) > 1;
SELECT col2,COUNT(*) FROM hw2_bcnf_2
GROUP BY col2
HAVING COUNT(*) > 1;
SELECT id1,COUNT(DISTINCT col1) FROM hw2_bcnf_2
GROUP BY id1
HAVING COUNT(DISTINCT col1) > 1;
SELECT id1,COUNT(DISTINCT col2) FROM hw2_bcnf_2
GROUP BY id1
HAVING COUNT(DISTINCT col2) > 1;
SELECT id2,COUNT(DISTINCT col1) FROM hw2_bcnf_2
GROUP BY id2
HAVING COUNT(DISTINCT col1) > 1;
SELECT id2,COUNT(DISTINCT col2) FROM hw2_bcnf_2
GROUP BY id2
HAVING COUNT(DISTINCT col2) > 1;
SELECT col1,COUNT(DISTINCT col2) FROM hw2_bcnf_2
GROUP BY col1
HAVING COUNT(DISTINCT col2)>1;
SELECT col2,COUNT(DISTINCT col1) FROM hw2_bcnf_2
GROUP BY col2
HAVING COUNT(DISTINCT col1)>1;
SELECT col1,COUNT(DISTINCT id1) FROM hw2_bcnf_2
GROUP BY col1
HAVING COUNT(DISTINCT id1)>1;
SELECT col1,COUNT(DISTINCT id2) FROM hw2_bcnf_2
GROUP BY col1
HAVING COUNT(DISTINCT id2)>1;
SELECT col2,COUNT(DISTINCT id1) FROM hw2_bcnf_2
GROUP BY col2
HAVING COUNT(DISTINCT id1)>1;
SELECT col2,COUNT(DISTINCT id2) FROM hw2_bcnf_2
GROUP BY col2
HAVING COUNT(DISTINCT id2)>1

hw2_compositepk
;
SELECT k1,k2,c FROM hw2_compositepk;
SELECT * FROM hw2_compositepk;
SELECT k1,k2,COUNT(*) FROM hw2_compositepk
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,c,COUNT(*) FROM hw2_compositepk
GROUP BY k1,k2,c
HAVING COUNT(*) > 1;
SELECT c,COUNT(*) FROM hw2_compositepk
GROUP BY c
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT c) FROM hw2_compositepk
GROUP BY k1
HAVING COUNT(DISTINCT c) > 1;
SELECT k2,COUNT(DISTINCT c) FROM hw2_compositepk
GROUP BY k2
HAVING COUNT(DISTINCT c) > 1;
SELECT c,COUNT(DISTINCT k1) FROM hw2_compositepk
GROUP BY c
HAVING COUNT(DISTINCT k1)>1;
SELECT c,COUNT(DISTINCT k2) FROM hw2_compositepk
GROUP BY c
HAVING COUNT(DISTINCT k2)>1

hw2_compositepk_2
;
SELECT k1,k2,a FROM hw2_compositepk_2;
SELECT * FROM hw2_compositepk_2;
SELECT k1,k2,COUNT(*) FROM hw2_compositepk_2
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,COUNT(*) FROM hw2_compositepk_2
GROUP BY k1,k2,a
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_compositepk_2
GROUP BY a
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_compositepk_2
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_compositepk_2
GROUP BY k2
HAVING COUNT(DISTINCT a) > 1;
SELECT a,COUNT(DISTINCT k1) FROM hw2_compositepk_2
GROUP BY a
HAVING COUNT(DISTINCT k1)>1;
SELECT a,COUNT(DISTINCT k2) FROM hw2_compositepk_2
GROUP BY a
HAVING COUNT(DISTINCT k2)>1

hw2_compositepk_3

hw2_easy
;
SELECT k,b FROM hw2_easy

hw2_easy_strings
;
SELECT k,a FROM hw2_easy_strings;
SELECT * FROM hw2_easy_strings;
SELECT k,COUNT(*) FROM hw2_easy_strings
GROUP BY k
HAVING COUNT(*) > 1;
SELECT k,a,COUNT(*) FROM hw2_easy_strings
GROUP BY k,a
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_easy_strings
GROUP BY a
HAVING COUNT(*) > 1;
SELECT a,COUNT(DISTINCT k) FROM hw2_easy_strings
GROUP BY a
HAVING COUNT(DISTINCT k)>1

hw2_empty
;
SELECT k1,k2,a,b FROM hw2_empty;
SELECT * FROM hw2_empty

hw2_invalidPKk_not1NF
;
SELECT k,a FROM hw2_invalidPKk_not1NF;
SELECT * FROM hw2_invalidPKk_not1NF;
SELECT k,COUNT(*) FROM hw2_invalidPKk_not1NF
GROUP BY k
HAVING COUNT(*) > 1;
SELECT k,a,COUNT(*) FROM hw2_invalidPKk_not1NF
GROUP BY k,a
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_invalidPKk_not1NF
GROUP BY a
HAVING COUNT(*) > 1

hw2_large_1
;
SELECT id,val1,val2,val3,val4,val5 FROM hw2_large_1;
SELECT * FROM hw2_large_1;
SELECT id,COUNT(*) FROM hw2_large_1
GROUP BY id
HAVING COUNT(*) > 1;
SELECT id,val1,val2,val3,val4,val5,COUNT(*) FROM hw2_large_1
GROUP BY id,val1,val2,val3,val4,val5
HAVING COUNT(*) > 1;
SELECT val1,COUNT(*) FROM hw2_large_1
GROUP BY val1
HAVING COUNT(*) > 1;
SELECT val2,COUNT(*) FROM hw2_large_1
GROUP BY val2
HAVING COUNT(*) > 1;
SELECT val3,COUNT(*) FROM hw2_large_1
GROUP BY val3
HAVING COUNT(*) > 1;
SELECT val4,COUNT(*) FROM hw2_large_1
GROUP BY val4
HAVING COUNT(*) > 1;
SELECT val5,COUNT(*) FROM hw2_large_1
GROUP BY val5
HAVING COUNT(*) > 1;
SELECT val1,COUNT(DISTINCT val2) FROM hw2_large_1
GROUP BY val1
HAVING COUNT(DISTINCT val2)>1;
SELECT val1,COUNT(DISTINCT val3) FROM hw2_large_1
GROUP BY val1
HAVING COUNT(DISTINCT val3)>1;
SELECT val1,COUNT(DISTINCT val4) FROM hw2_large_1
GROUP BY val1
HAVING COUNT(DISTINCT val4)>1

hw2_large_2
;
SELECT k1,k2,a,b,c,d FROM hw2_large_2;
SELECT * FROM hw2_large_2;
SELECT k1,k2,COUNT(*) FROM hw2_large_2
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,b,c,d,COUNT(*) FROM hw2_large_2
GROUP BY k1,k2,a,b,c,d
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_large_2
GROUP BY a
HAVING COUNT(*) > 1;
SELECT b,COUNT(*) FROM hw2_large_2
GROUP BY b
HAVING COUNT(*) > 1;
SELECT c,COUNT(*) FROM hw2_large_2
GROUP BY c
HAVING COUNT(*) > 1;
SELECT d,COUNT(*) FROM hw2_large_2
GROUP BY d
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_large_2
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_large_2
GROUP BY k1
HAVING COUNT(DISTINCT b) > 1

hw2_large_3
;
SELECT k1,k2,a,b,c,d,e,f,g,h,l,m FROM hw2_large_3;
SELECT * FROM hw2_large_3;
SELECT k1,k2,COUNT(*) FROM hw2_large_3
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,b,c,d,e,f,g,h,l,m,COUNT(*) FROM hw2_large_3
GROUP BY k1,k2,a,b,c,d,e,f,g,h,l,m
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_large_3
GROUP BY a
HAVING COUNT(*) > 1;
SELECT b,COUNT(*) FROM hw2_large_3
GROUP BY b
HAVING COUNT(*) > 1;
SELECT c,COUNT(*) FROM hw2_large_3
GROUP BY c
HAVING COUNT(*) > 1;
SELECT d,COUNT(*) FROM hw2_large_3
GROUP BY d
HAVING COUNT(*) > 1;
SELECT e,COUNT(*) FROM hw2_large_3
GROUP BY e
HAVING COUNT(*) > 1;
SELECT f,COUNT(*) FROM hw2_large_3
GROUP BY f
HAVING COUNT(*) > 1;
SELECT g,COUNT(*) FROM hw2_large_3
GROUP BY g
HAVING COUNT(*) > 1;
SELECT h,COUNT(*) FROM hw2_large_3
GROUP BY h
HAVING COUNT(*) > 1;
SELECT l,COUNT(*) FROM hw2_large_3
GROUP BY l
HAVING COUNT(*) > 1;
SELECT m,COUNT(*) FROM hw2_large_3
GROUP BY m
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_large_3
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1

hw2_not2nf
;
SELECT k1,k2,a FROM hw2_not2nf;
SELECT * FROM hw2_not2nf;
SELECT k1,k2,COUNT(*) FROM hw2_not2nf
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,COUNT(*) FROM hw2_not2nf
GROUP BY k1,k2,a
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_not2nf
GROUP BY a
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_not2nf
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1

hw2_not2nf_difficult
;
SELECT k1,k2,a,b FROM hw2_not2nf_difficult;
SELECT * FROM hw2_not2nf_difficult;
SELECT k1,k2,COUNT(*) FROM hw2_not2nf_difficult
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,b,COUNT(*) FROM hw2_not2nf_difficult
GROUP BY k1,k2,a,b
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_not2nf_difficult
GROUP BY a
HAVING COUNT(*) > 1;
SELECT b,COUNT(*) FROM hw2_not2nf_difficult
GROUP BY b
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_not2nf_difficult
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_not2nf_difficult
GROUP BY k1
HAVING COUNT(DISTINCT b) > 1

hw2_not2nf_easy
;
SELECT k1,k2,a FROM hw2_not2nf_easy;
SELECT * FROM hw2_not2nf_easy;
SELECT k1,k2,COUNT(*) FROM hw2_not2nf_easy
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,COUNT(*) FROM hw2_not2nf_easy
GROUP BY k1,k2,a
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_not2nf_easy
GROUP BY a
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_not2nf_easy
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1

hw2_onerow
;
SELECT k1,k2,a,b,c,d,e,f,g,h FROM hw2_onerow;
SELECT * FROM hw2_onerow

hw2_pkbad_3
;
SELECT k,a FROM hw2_pkbad_3;
SELECT * FROM hw2_pkbad_3;
SELECT k,COUNT(*) FROM hw2_pkbad_3
GROUP BY k
HAVING COUNT(*) > 1;
SELECT k,a,COUNT(*) FROM hw2_pkbad_3
GROUP BY k,a
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_pkbad_3
GROUP BY a
HAVING COUNT(*) > 1

hw2_pkbad_4
;
SELECT k1,k2,a FROM hw2_pkbad_4;
SELECT * FROM hw2_pkbad_4;
SELECT k1,k2,COUNT(*) FROM hw2_pkbad_4
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,COUNT(*) FROM hw2_pkbad_4
GROUP BY k1,k2,a
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_pkbad_4
GROUP BY a
HAVING COUNT(*) > 1

hw2_pkeasy
;
SELECT k,ab FROM hw2_pkeasy;
SELECT * FROM hw2_pkeasy;
SELECT k,COUNT(*) FROM hw2_pkeasy
GROUP BY k
HAVING COUNT(*) > 1;
SELECT k,ab,COUNT(*) FROM hw2_pkeasy
GROUP BY k,ab
HAVING COUNT(*) > 1;
SELECT ab,COUNT(*) FROM hw2_pkeasy
GROUP BY ab
HAVING COUNT(*) > 1;
SELECT ab,COUNT(DISTINCT k) FROM hw2_pkeasy
GROUP BY ab
HAVING COUNT(DISTINCT k)>1

hw2_strings
;
SELECT k1,k2,a,b,c,d,e,f FROM hw2_strings;
SELECT * FROM hw2_strings;
SELECT k1,k2,COUNT(*) FROM hw2_strings
GROUP BY k1,k2
HAVING COUNT(*) > 1;
SELECT k1,k2,a,b,c,d,e,f,COUNT(*) FROM hw2_strings
GROUP BY k1,k2,a,b,c,d,e,f
HAVING COUNT(*) > 1;
SELECT a,COUNT(*) FROM hw2_strings
GROUP BY a
HAVING COUNT(*) > 1;
SELECT b,COUNT(*) FROM hw2_strings
GROUP BY b
HAVING COUNT(*) > 1;
SELECT c,COUNT(*) FROM hw2_strings
GROUP BY c
HAVING COUNT(*) > 1;
SELECT d,COUNT(*) FROM hw2_strings
GROUP BY d
HAVING COUNT(*) > 1;
SELECT e,COUNT(*) FROM hw2_strings
GROUP BY e
HAVING COUNT(*) > 1;
SELECT f,COUNT(*) FROM hw2_strings
GROUP BY f
HAVING COUNT(*) > 1;
SELECT k1,COUNT(DISTINCT a) FROM hw2_strings
GROUP BY k1
HAVING COUNT(DISTINCT a) > 1;
SELECT k1,COUNT(DISTINCT b) FROM hw2_strings
GROUP BY k1
HAVING COUNT(DISTINCT b) > 1;
SELECT k1,COUNT(DISTINCT c) FROM hw2_strings
GROUP BY k1
HAVING COUNT(DISTINCT c) > 1;
SELECT k1,COUNT(DISTINCT d) FROM hw2_strings
GROUP BY k1
HAVING COUNT(DISTINCT d) > 1;
SELECT k1,COUNT(DISTINCT e) FROM hw2_strings
GROUP BY k1
HAVING COUNT(DISTINCT e) > 1;
SELECT k1,COUNT(DISTINCT f) FROM hw2_strings
GROUP BY k1
HAVING COUNT(DISTINCT f) > 1;
SELECT k2,COUNT(DISTINCT a) FROM hw2_strings
GROUP BY k2
HAVING COUNT(DISTINCT a) > 1;
SELECT k2,COUNT(DISTINCT b) FROM hw2_strings
GROUP BY k2
HAVING COUNT(DISTINCT b) > 1;
SELECT k2,COUNT(DISTINCT c) FROM hw2_strings
GROUP BY k2
HAVING COUNT(DISTINCT c) > 1;
SELECT k2,COUNT(DISTINCT d) FROM hw2_strings
GROUP BY k2
HAVING COUNT(DISTINCT d) > 1
